/* eslint-disable @typescript-eslint/no-non-null-asserted-optional-chain */
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import LoadingButton from "@/components/ui/loading-button";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import { BeneficiaryData } from "@/lib/types";
import { beneficiarySchema, BeneficiarySchema } from "@/lib/validation";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import FieldGender from "./field-gender";
import FieldSaccoGroup from "./field-sacco-group";
import FieldStatus from "./field-status";
import { useUpsertBeneficiaryMutation } from "./mutation";

interface FormAddEditBeneficiaryProps {
  open: boolean;
  setOpen: (open: boolean) => void;
  beneficiaryToEdit?: BeneficiaryData;
  saccoGroupId?: string;
}
export default function FormAddEditBeneficiary({
  open,
  setOpen,
  beneficiaryToEdit,
  saccoGroupId,
}: FormAddEditBeneficiaryProps) {
  const form = useForm<BeneficiarySchema>({
    resolver: zodResolver(beneficiarySchema),
    values: {
      id: beneficiaryToEdit?.id || "",
      fullName: beneficiaryToEdit?.fullName || "",
      gender: beneficiaryToEdit?.gender!,
      memberId: beneficiaryToEdit?.memberId || "",
      saccoGroupId: saccoGroupId || beneficiaryToEdit?.saccoGroupId || "",
      status: beneficiaryToEdit?.status!,
      contact: beneficiaryToEdit?.contact || "",
      email: beneficiaryToEdit?.email || "",
      nin: beneficiaryToEdit?.nin || "",
      subsistence: beneficiaryToEdit?.subsistence || "",
    },
  });

  const { isPending, mutate } = useUpsertBeneficiaryMutation();
  function onSubmit(input: BeneficiarySchema) {
    mutate(
      { ...input, saccoGroupId: saccoGroupId! },
      {
        onSuccess() {
          setOpen(false);
        },
      },
    );
  }

  return (
    <Sheet open={open} onOpenChange={setOpen}>
      <SheetContent side="right">
        <SheetHeader>
          <SheetTitle>
            {beneficiaryToEdit ? "Update beneficiary" : "Add beneficiary"}
          </SheetTitle>
        </SheetHeader>
        <div className="max-w-xl px-3 mx-auto overflow-y-auto py-4  w-full">
          <Form {...form}>
            {/* <pre>{JSON.stringify(form.getValues(), null, 2)}</pre> */}
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4 ">
              <FormField
                control={form.control}
                name="fullName"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel required>Beneficiary fullname</FormLabel>
                    <FormControl>
                      <Input placeholder="e.g., Okurut Vincent" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="memberId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel required>Member Id</FormLabel>
                    <FormControl>
                      <Input
                        placeholder="autogenerated number by PDMIS"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="nin"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>National ID Number (NIN)</FormLabel>
                    <FormControl>
                      <Input placeholder="e.g., CF001221050AZL" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FieldGender form={form} />
              <FormField
                control={form.control}
                name="contact"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Contact</FormLabel>
                    <FormControl>
                      <Input placeholder="e.g., 2567701297527" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="email"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel required>Email</FormLabel>
                    <FormControl>
                      <Input type="email" placeholder="e.g., someone@gmail.com" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FieldStatus form={form} />
              <FormField
                control={form.control}
                name="subsistence"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Subsistence</FormLabel>
                    <FormControl>
                      <Input placeholder="this is PDMIS generated" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FieldSaccoGroup
                form={form}
                lockSaccoGroupField={!!saccoGroupId}
              />
              <div className="flex w-full justify-end items-center gap-4">
                <LoadingButton
                  loading={isPending}
                  disabled={!form.formState.isDirty}
                >
                  {beneficiaryToEdit ? "Update beneficiary" : "Add beneficiary"}
                </LoadingButton>
              </div>
            </form>
          </Form>
        </div>
      </SheetContent>
    </Sheet>
  );
}
