import ResponsiveDrawer from "@/components/responsive-drawer";
import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import {
  Item,
  ItemActions,
  ItemContent,
  ItemDescription,
  ItemTitle,
} from "@/components/ui/item";
import LoadingButton from "@/components/ui/loading-button";
import {
  BulkBeneficiaryUploadArray,
  bulkBeneficiaryUploadSchema,
  BulkBeneficiaryUploadSchema,
} from "@/lib/validation";
import { zodResolver } from "@hookform/resolvers/zod";
import { useTransition } from "react";
import { useFieldArray, useForm, UseFormReturn } from "react-hook-form";
import FieldGender from "./field-gender";
import FieldSaccoGroup from "./field-sacco-group";
import FieldStatus from "./field-status";

interface FormAddEditPersonProps {
  open: boolean;
  setOpen: (open: boolean) => void;
  item?: BulkBeneficiaryUploadSchema;
  form: UseFormReturn<BulkBeneficiaryUploadArray>;
  index?: number;
}
export default function FormAddEditPerson({
  open,
  setOpen,
  item,
  form,
  index,
}: FormAddEditPersonProps) {
  const [isPending, startTransition] = useTransition();
  const { append, update, remove } = useFieldArray({
    control: form.control,
    name: "beneficiaries",
  });
  const form2 = useForm<BulkBeneficiaryUploadSchema>({
    resolver: zodResolver(bulkBeneficiaryUploadSchema),
    defaultValues: {
      ...item,
     
    },
    shouldUnregister: true,
  });

  function onSubmit(input: BulkBeneficiaryUploadSchema) {
    startTransition(() => {
      if (!!item) {
        update(index!, input);
      } else {
        append(input);
        form2.reset();
      }
      setOpen(false);
    });
  }

  return (
    <ResponsiveDrawer
      open={open}
      setOpen={setOpen}
      title={item ? "Edit Beneficiary" : "Add Beneficiary"}
    >
      {!!item && (
        <Item variant={"muted"} className="">
          <ItemContent>
            <ItemTitle> Dangerous action</ItemTitle>
            <ItemDescription>
              Please proceed with caution. By clicking on remove button, this
              staff will be removed from the list
            </ItemDescription>
          </ItemContent>
          <ItemActions>
            <Button variant={"destructive"} onClick={() => remove(index)}>
              Remove {item.fullname || "this staff"}
            </Button>
          </ItemActions>
        </Item>
      )}
      <Form {...form2}>
        {/* <pre>{JSON.stringify(form2.formState.errors, null, 2)}</pre>
        <pre>{JSON.stringify(form2.watch(), null, 2)}</pre> */}
        <form className="space-y-4 p-4" onSubmit={form2.handleSubmit(onSubmit)}>
          <div className="flex flex-col *:flex-1 md:flex-row gap-4">
            <div className="space-y-4">
              <FormField
                control={form2.control}
                name="fullname"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel required>Beneficiary fullname</FormLabel>
                    <FormControl>
                      <Input placeholder="e.g., Okurut Vincent" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form2.control}
                name="memberId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel required>Member Id</FormLabel>
                    <FormControl>
                      <Input
                        placeholder="autogenerated number by PDMIS"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form2.control}
                name="nin"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>National ID Number (NIN)</FormLabel>
                    <FormControl>
                      <Input placeholder="e.g., CF001221050AZL" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FieldGender form={form2} />
              <FormField
                control={form2.control}
                name="contact"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Contact</FormLabel>
                    <FormControl>
                      <Input placeholder="e.g., 2567701297527" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form2.control}
                name="email"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel required>Email</FormLabel>
                    <FormControl>
                      <Input
                        type="email"
                        placeholder="e.g., someone@gmail.com"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FieldStatus form={form2} />{" "}
              <FormField
                control={form2.control}
                name="subsistence"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Subsistence</FormLabel>
                    <FormControl>
                      <Input placeholder="this is PDMIS generated" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FieldSaccoGroup lockSaccoGroupField={false} form={form2} />
              <FormField
                control={form2.control}
                name="district"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>District</FormLabel>
                    <FormControl>
                      <Input placeholder="e.g., Lira City" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form2.control}
                name="subCounty"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Sub County</FormLabel>
                    <FormControl>
                      <Input
                        placeholder="e.g., City West Division"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form2.control}
                name="parish"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Parish</FormLabel>
                    <FormControl>
                      <Input placeholder="e.g., Jinja Camp ward" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form2.control}
                name="village"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Village</FormLabel>
                    <FormControl>
                      <Input placeholder="e.g., Ireda Central" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />{" "} <FormField
                control={form2.control}
                name="createdAt"
                render={({ field }) => (
                  <FormItem className="hidden">
                    <FormLabel>Created at</FormLabel>
                    <FormControl>
                      {/* <Input placeholder="e.g., Ireda Central" {...field} /> */}
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />{" "}
            </div>
          </div>
          <div className="flex justify-end w-full items-center">
            <LoadingButton
              loading={isPending}
              type="button"
              onClick={() => form2.handleSubmit(onSubmit)()}
            >
              {item ? "Make Beneficiary changes" : "Add this Beneficiary"}
            </LoadingButton>
          </div>
        </form>
      </Form>
    </ResponsiveDrawer>
  );
}
